[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
poc_orderbook = "5iE7GeaittdpRErnR45x2h9Bj4fmLgqvxmjfk3oSVkXq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"
